name: osv-scan-go

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clone latest release
      run: |
        release_url=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/google/osv-scanner/releases/latest)
        latest_release=$(basename $release_url)
        git clone -b $latest_release -- https://github.com/google/osv-scanner.git $GITHUB_WORKSPACE/repo
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
    - name: Build osv-scanner
      run: |
        cd $GITHUB_WORKSPACE/repo
        go mod download
        go build -o osv-scanner ./cmd/osv-scanner/
    - name: Run scan
      continue-on-error: true
      run: $GITHUB_WORKSPACE/repo/osv-scanner --lockfile=$GITHUB_WORKSPACE/src/Brie.Ui/ClientApp/package-lock.json --json > $GITHUB_WORKSPACE/scan_results.json
    - uses: actions/upload-artifact@v3
      with:
        name: osv-scanner-results
        path: ./scan_results.json
